############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "Ã€ propos"
url = "#about"
weight = 2

[[main]]
name = "Contact"
url = "#contacts"
weight = 3

[[main]]
name = "GPM Holding"
url = "https://gp-maroc.ma/"
weight = 3

# footer menu
[[footer_menu]]
name = "GPM Holding"
url = "https://gp-maroc.ma/"
weight = 1

# footer bottom links
[[footer]]
name = "Conditions d'utilisation"
url = "terms/"
weight = 1
