########################### Default parameters ######################
logo = "images/sondiale-w-background-02-01.png"
logo_width = "150px"
logo_footer = "images/sondiale-w-background-02-01-ffffff.png"
favicon = "images/favicon.png"
page_sharing_image = "images/backgrounds/page-sharing.jpg"
# top header
top_header = false
# Meta data
description = "Sundial represents GPM Holdingâ€™s initiative to develop polysilicon production capacity in Morocco."
author = "Sondiale"
# contact info
address = "183 AVENUE PRINCE HERITIER CENTRE NREA LOCAL N 13 RDC, Tanger"
mobile = "0539 94 59 52"
email = "khaoula.zayoun@gp-maroc.ma"
# contact form action
contact_form_action = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSeGwhzOaX9eKvI-Ij92LF9ZBzf_h8jOg4ALLyyIUYOJNYtzxg/formResponse" # contact form works with https://formspree.io

# Google Tag Manager
gtm = "" # GTM-XXXXXXXX

# Global date parameters
year = 2026
cookie_consent = false

# page sidebar quick contact form
quick_contact = true
# search
search = false

# Main section
mainSections = ["blog"]

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "get a quote"
link = "#contacts"

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
map_marker_name = "Bexer"

########################### social icon ############################
#[[social]]
#icon = "fab fa-facebook"
#link = "https://facebook.com/"
#
#[[social]]
#icon = "fab fa-twitter"
#link = "https://twitter.com/"
#
#[[social]]
#icon = "fab fa-instagram"
#link = "https://instagram.com/"


